/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Infinity.gltf 
Author: gavinpgamer1 (https://sketchfab.com/gavinpgamer1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/unsc-infinity-0a4fc6fb48e341f4b4defb3e769054a1
Title: UNSC Infinity
*/

import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { Mesh } from 'three'



type GLTFResult = {
  nodes: {
    Object_2: Mesh
    Object_3: Mesh
    Object_4: Mesh
    Object_5: Mesh
    Object_6: Mesh
    Object_7: Mesh
    Object_8: Mesh
    Object_9: Mesh
    Object_10: Mesh
    Object_11: Mesh
    Object_12: Mesh
    Object_13: Mesh
    Object_14: Mesh
    Object_15: Mesh
    Object_16: Mesh
    Object_17: Mesh
    Object_18: Mesh
    Object_19: Mesh
    Object_20: Mesh
    Object_21: Mesh
    Object_22: Mesh
  }

  materials: {
    Forerunner1Mtl: THREE.Material
    ArcherYellowish1Mtl: THREE.Material
    LightHull1Mtl: THREE.Material
    DarkHull1Mtl: THREE.Material
    Engineyeah1Mtl: THREE.Material
    HangarLights1Mtl: THREE.Material
    HullLights1Mtl: THREE.Material
    Bronze1Mtl: THREE.Material
    MainHull1Mtl: THREE.Material
    HullLights2Mtl: THREE.Material
  }
}


export default function Model(props: JSX.IntrinsicElements['group']) {
  
  const { nodes, materials } = useGLTF('public/infinitymodel/Infinity.gltf')as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Forerunner1Mtl} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.ArcherYellowish1Mtl} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.LightHull1Mtl} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.DarkHull1Mtl} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Engineyeah1Mtl} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.HangarLights1Mtl} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.HullLights1Mtl} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Bronze1Mtl} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Bronze1Mtl} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.MainHull1Mtl} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.MainHull1Mtl} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.MainHull1Mtl} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.MainHull1Mtl} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.MainHull1Mtl} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.MainHull1Mtl} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.MainHull1Mtl} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.MainHull1Mtl} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.MainHull1Mtl} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.MainHull1Mtl} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.MainHull1Mtl} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.HullLights2Mtl} />
      </group>
    </group>
  )
}

useGLTF.preload('/Infinity.gltf')
