/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Fury.gltf 
Author: Hangar.b.productions (https://sketchfab.com/hangar.b.productions)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/super-starfury-fae71394fb02478ba269ccddf39c5d54
Title: Super Starfury
*/

import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { Mesh } from 'three'
import * as THREE from 'three'



type GLTFResult = GLTF & {
  nodes: {
    Fuselage_SuperStarFury_0: Mesh
    Fuselage_White_0: Mesh
    Fuselage_RED_0: Mesh
    Engines_SuperStarFury_0: Mesh
    Engines_SuperStarFury_0_1: Mesh
    Engines_BLUE_0: Mesh
    Engines_RED_0: Mesh
    Cockpit_SuperStarFury_0: Mesh
    Cockpit_RED_0: Mesh
    Glass_Canopy_Glass_0: Mesh
    Glass_Glass_0: Mesh
    'Pilot_(2)_Pilot_0': Mesh
    'Pilot_(2)_Alum_0': Mesh
    'Pilot_(2)_Glass_0': Mesh
    'Pilot_(2)_DarkAlum_0': Mesh
    Missiles_SuperStarFury_0: Mesh
    Main_Thrust_Thrust_0: Mesh
    Main_Thrust_ThrustCenter_0: Mesh
  }
  materials: {
    SuperStarFury: THREE.Material
    White: THREE.Material
    material: THREE.Material
    BLUE: THREE.Material
    RED: THREE.Material
    Canopy_Glass: THREE.Material
    Glass: THREE.Material
    Pilot: THREE.Material
    Alum: THREE.Material
    DarkAlum: THREE.Material
    Thrust: THREE.Material
    ThrustCenter: THREE.Material
  }
}


export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('public/furymodel/Fury.gltf')as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.438, -0.174, -0.021]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          {/* <group position={[0, 0, 335]} scale={[1, 0.86, 1]}> */}
          <group position={[0, 0, 0]} scale={[0.5,0.3,0.5]}>

            <mesh geometry={nodes.Fuselage_SuperStarFury_0.geometry} material={materials.SuperStarFury} />
            <mesh geometry={nodes.Fuselage_White_0.geometry} material={materials.White} />
            <mesh geometry={nodes.Fuselage_RED_0.geometry} material={materials.material} />
          </group>
          <group position={[0, 0, 0]}>
            <mesh geometry={nodes.Engines_SuperStarFury_0.geometry} material={materials.SuperStarFury} />
            <mesh geometry={nodes.Engines_SuperStarFury_0_1.geometry} material={materials.SuperStarFury} />
            <mesh geometry={nodes.Engines_BLUE_0.geometry} material={materials.BLUE} />
            <mesh geometry={nodes.Engines_RED_0.geometry} material={materials.material} />
          </group>
          <group position={[0, 0, 0]}>
            <mesh geometry={nodes.Cockpit_SuperStarFury_0.geometry} material={materials.SuperStarFury} />
            <mesh geometry={nodes.Cockpit_RED_0.geometry} material={materials.material} />
          </group>
          <group position={[0, 0, 0]}>
            <mesh geometry={nodes.Glass_Canopy_Glass_0.geometry} material={materials.Canopy_Glass} />
            <mesh geometry={nodes.Glass_Glass_0.geometry} material={materials.Glass} />
          </group>
          <group position={[0, 0, 0]}>
            <mesh geometry={nodes['Pilot_(2)_Pilot_0'].geometry} material={materials.Pilot} />
            <mesh geometry={nodes['Pilot_(2)_Alum_0'].geometry} material={materials.Alum} />
            <mesh geometry={nodes['Pilot_(2)_Glass_0'].geometry} material={materials.Glass} />
            <mesh geometry={nodes['Pilot_(2)_DarkAlum_0'].geometry} material={materials.DarkAlum} />
          </group>
          <mesh geometry={nodes.Missiles_SuperStarFury_0.geometry} material={materials.SuperStarFury} position={[0, 0, 0]} />
          <mesh geometry={nodes.Main_Thrust_Thrust_0.geometry} material={materials.Thrust} />
          <mesh geometry={nodes.Main_Thrust_ThrustCenter_0.geometry} material={materials.ThrustCenter} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Fury.gltf')
