/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Cop.gltf 
Author: Mateusz Woliński (https://sketchfab.com/jeandiz)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/cyborg-cop-7a7ed988d149408ebe198c21f8040939
Title: Cyborg Cop
*/

import React, { JSX } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'
import { Mesh, Object3D, SkinnedMesh } from 'three'
import * as THREE from 'three'


type GLTFResult = GLTF & {
  nodes: {
    [key: string]: Mesh | SkinnedMesh | Object3D,
    
  }
  materials: {
    [key: string]: THREE.Material
  }
}


export default function Model(props: JSX.IntrinsicElements['group']) {
  const { scene } = useGLTF('public/copmodel/Cop.gltf')as GLTFResult
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[-0.414, 1.358, 0.622]} rotation={[1.661, -0.199, 0.386]} scale={0.023}>
        <group position={[0, 0.082, 0.157]} rotation={[0.32, 0, 0]}>
          <mesh geometry={(nodes.Object_7 as Mesh ).geometry} material={materials.pistol1} />
          <mesh geometry={(nodes.Object_9 as Mesh ).geometry} material={materials.pistol1} position={[0, 0.089, -3.186]} rotation={[-0.614, 0, 0]} />
          <mesh geometry={(nodes.Object_11 as Mesh ).geometry} material={materials.pistol1} position={[-0.279, -1.559, -5.997]} rotation={[-0.534, -0.017, -0.578]} />
          <mesh geometry={(nodes.Object_13 as Mesh ).geometry} material={materials.pistol1} position={[-0.717, -4.114, -8.552]} rotation={[2.398, 0.761, -1.267]} />
          <mesh geometry={(nodes.Object_15 as Mesh ).geometry} material={materials.pistol1} position={[-0.607, -2.824, -7.339]} rotation={[0.192, -0.601, 1.285]} />
          <mesh geometry={(nodes.Object_17 as Mesh ).geometry} material={materials.pistol1} position={[-0.143, -0.535, -4.77]} rotation={[2.069, 0.948, -2.455]} />
          <mesh geometry={(nodes.Object_19 as Mesh ).geometry} material={materials.pistol1} position={[-1.262, -5.578, -9.806]} rotation={[-0.497, 0.801, -0.916]} />
        </group>
        <mesh geometry={(nodes.Object_5 as Mesh ).geometry} material={materials.pistol1} position={[0, -0.212, 0.222]} />
        <mesh geometry={(nodes.Object_21 as Mesh ).geometry} material={materials.pistol1} position={[0, -0.492, -3.137]} />
        <mesh geometry={(nodes.Object_23 as Mesh ).geometry} material={materials.pistol1} position={[0, 2.621, -2.067]} rotation={[0.349, 0, 0]} />
      </group>
      <group position={[0, 0, -0.007]}>
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh geometry={(nodes.Object_28 as Mesh ).geometry} material={materials.Body} skeleton={(nodes.Object_28 as SkinnedMesh).skeleton} />
        <skinnedMesh geometry={(nodes.Object_29 as Mesh ).geometry} material={materials.headgear} skeleton={(nodes.Object_29 as SkinnedMesh).skeleton} />
        <skinnedMesh geometry={(nodes.Object_30 as Mesh ).geometry} material={materials.gear} skeleton={(nodes.Object_30 as SkinnedMesh).skeleton} />
        <skinnedMesh geometry={(nodes.Object_31 as Mesh ).geometry} material={materials.Gear_2} skeleton={(nodes.Object_31 as SkinnedMesh).skeleton} />
        <skinnedMesh geometry={(nodes.Object_32 as Mesh ).geometry} material={materials.Vest_and_Belt} skeleton={(nodes.Object_32 as SkinnedMesh).skeleton} />
        <skinnedMesh geometry={(nodes.Object_33 as Mesh ).geometry} material={materials.Hood} skeleton={(nodes.Object_33 as SkinnedMesh).skeleton} />
        <skinnedMesh geometry={(nodes.Object_34 as Mesh ).geometry} material={materials.Boot} skeleton={(nodes.Object_34 as SkinnedMesh).skeleton} />
      </group>
      <mesh geometry={(nodes.Object_101 as Mesh ).geometry} material={materials.muzzle_flashes} position={[-0.512, 1.423, 0.908]} rotation={[0, -0.658, 0]} />
    </group>
  )
}

useGLTF.preload('/Cop.gltf')
