/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Lightblade.gltf 
Author: Robin Butler (https://sketchfab.com/StarTrekGuy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lightblade-cruiser-xl4t-mark-1-0b2af30e4df448358b16d91066e81ea9
Title: LightBlade Cruiser XL4T - Mark 1
*/

import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { Mesh } from 'three'
import * as THREE from 'three'



type GLTFResult = GLTF & {
  nodes: {
    Torus_0: Mesh
    Torus_0_1: Mesh
    Torus_1: Mesh
    Torus_1_1: Mesh
    Torus_1_2: Mesh
    Torus_2: Mesh
    Torus_3: Mesh
  }
  materials: {
    ['Material.000']: THREE.Material
    ['Material.007']: THREE.Material
    ['Material.008']: THREE.Material
  }
}

{/* <group position={[-2.733, -0.11, -5.52]} rotation={[-1.32, 0.018, -0.793]}>
        <group position={[5.304, 6.613, 0.782]} rotation={[-0.183, -0.173, -0.781]} scale={0.287}>
           */}

export default  function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('public/lightblademodel/Lightblade.gltf') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0,0,0]} rotation={[0,0,0]}>
        <group position={[0,0,0]} rotation={[0,0,0]} scale={0.287}>
          <mesh geometry={nodes.Torus_0.geometry} material={materials['Material.000']} />
          <mesh geometry={nodes.Torus_0_1.geometry} material={materials['Material.000']} />
          <mesh geometry={nodes.Torus_1.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Torus_1_1.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Torus_1_2.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Torus_2.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.Torus_3.geometry} material={materials['Material.007']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Lightblade.gltf')
