/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Spacev.gltf 
Author: Mstr Ananas (https://sketchfab.com/mstr_ananas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spaceship-version-0-e7dfaff507ae4858ba7fa26105bd9d26
Title: Spaceship (version 0)
*/

import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { Mesh } from 'three'
import * as THREE from 'three'



type GLTFResult = {
  nodes: {
    Spaceship_0: Mesh
    Spaceship_1: Mesh
    Spaceship_2: Mesh
  }
  materials: {
    Lights: THREE.Material
    Glass: THREE.Material
    Metal_2: THREE.Material
  }
}


export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('public/spaceshipversionmodel/Spacev.gltf')as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.563, 0, -0.016]} scale={3.016}>
        <group position={[1.114, 1.18, -0.366]} rotation={[0, 0, -0.024]}>
          <mesh geometry={nodes.Spaceship_0.geometry} material={materials.Lights} />
          <mesh geometry={nodes.Spaceship_1.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Spaceship_2.geometry} material={materials.Metal_2} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Spacev.gltf')
