/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Spaceship.gltf 
Author: Pump (https://sketchfab.com/Pump)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-ship-70f79932121d47ac998aeec03ede6e3c
Title: Space Ship
*/

import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib';
import { Mesh } from 'three';



type GLTFResult = GLTF & {
  nodes: {
    Object_3: Mesh;
    Object_4: Mesh;
    Object_5: Mesh;
    Object_6: Mesh;
  };
  materials: {
    blanco: THREE.Material;
    motores: THREE.Material;
    sensores: THREE.Material;
    sensores_1: THREE.Material;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('public/spaceshipmodel/Spaceship.gltf')as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <group position={[-9589.738, -11905.776, -6412.199]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.blanco} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.motores} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.sensores} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.sensores_1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Spaceship.gltf')
