/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Wing.gltf 
Author: Muhammad Fayyaz Baig (https://sketchfab.com/baig.muhammadfayyaz)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/robo-wings-869cd2944e7b43e391167783d5a9dc0d
Title: Robo Wings
*/

import React, { ComponentProps, JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { LineSegments, Material, Mesh } from 'three'


type GLTFResult = GLTF & {
  nodes: {
    Object_2: LineSegments
    Object_3: Mesh
  }
  materials: {
    Rig1Mtl: Material
  }
}

type Props = ComponentProps<'group'>



export default function Model(props : JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('public/wingmodel/Wing.gltf')as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <lineSegments geometry={nodes.Object_2.geometry} material={materials.Rig1Mtl} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Rig1Mtl} />
      </group>
    </group>
  )
}

useGLTF.preload('/Wing.gltf')
